CREATE TABLE MEMBER (
    MEMBER_ID    VARCHAR2(20)   CONSTRAINT PK_MEMBER PRIMARY KEY,  -- 기본키
    MEMBER_PWD   VARCHAR2(20)   CONSTRAINT NN_MEMBER_PWD NOT NULL, -- 비밀번호 필수
    MEMBER_EMAIL VARCHAR2(50)   CONSTRAINT UQ_MEMBER_EMAIL UNIQUE, -- 이메일은 유니크
    MEMBER_NAME  VARCHAR2(20)   CONSTRAINT NN_MEMBER_NAME NOT NULL -- 이름 필수
);